final Map<String, String> english = {
  "DomainNotValid": "Domain not valid",

  "Login": "Login",
  "Logout": "Logout",
  "LogoutOfYourAccount": "Log out of your account?",
  "Domain": "Domain",
  "Username": "Username",
  "Password": "Password",
  "Okay": "Okay",
  "Confirm": "Confirm",
  "Success": "Success",
  "Failure": "Failure",
  "Close": "Close",
  "SomethingWentWrong":
      "Something when went. Please check and try again later or contact to our support center.",
  "ComingSoon":"Coming Soon!",
  "FeatureComingSoon":"This feature will available soon.",

  // api respose
  "Login failed!": "Login failed!",
  "The user name or password provided is incorrect!":
      "The user name or password provided is incorrect!",

  // feature check stock
  "CheckStock": "Check stock",
  "CheckStockDescirption":
      "check stock availability and location in the warehouse.",
  "InvalidCode": "Invalid code",
  "ScanningCode": "Scanning Code",
  "AimYourCameraOnQrCodeBarcodeToCheck":
      "Please aim your camera on Qr Code/Barcode.",
  "MyResponseLocation": "My response location",
  "ScanninOtherLocationgCode": "Other location",
  "AvailableQuantity": "Available quantity",
  "QuantityOnHand": "Quantity on hand",
  "ScanCodeToCheckStock": "Scan code to check stock",
  "RelatedItem": "Related Item",

  // feature count
  "Count": "Count",
  "Counts": "Counts",
  "CountQuantity": "Count Quantity",
  "CountDescirption": "Start count your item.",
  "ItemCount": "Item count",
  "ItemToCount": "Item to count",
  "Pending": "Pending",
  "Inprocess": "Inprocess",
  "PendingRecount": "Pending Recount",
  "ProcessRecount": "Process Recount",
  "Recount": "Recount",
  "ItemCode": "Item code",
  "ItemBarcode": "Item barcode",
  "ItemDescription": "Item description",
  "LastCount": "Last count",
  "All": "All",
  "Counted": "Counted",
  "Uncounted": "Uncounted",
  "Matched": "Matched",
  "Unmatched": "Unmatched",
  "Finish": "Finish",
  "CountHistory": "Count history",
  "ViewAll": "View all",
  "CountType": "Count Type",
  "AutoIncrease": "Auto Increase",
  "ManualInput": "Manual Input",
  "FinishCountSuccess": "Finish count success!",
  "StartCount": "Start count",
  "StartCountMsg": "Start counting process?",
  "CountNotYetStart": "Count not yet start",
  "CountNotYetStartMsg":
      "This count not started yet please wait until this count start.",
  "FinishCount": "Finish Count",

  "Scan": "Scan",
  "AutoScan": "Auto Scan",
  "Product": "Product",
  "Add": "Add",
  "Replace": "Replace",
  "FinishCountAlertMessage":
      "Are you sure to finish counting with above result, this action can’t be undone?",

  "Filter": "Filter",
  "Brand": "Brand",
  "Category": "Category",
  "SortBy": "Sort by",
  "Reset": "Reset",
  "Start": "Start",
  "Cancel": "Cancel",
  "Search": "Search...",
  "Quantity": "Quantity",

  "AppVersion": "App version",
  "AppVersionUpToDate": "Your app version {0} is up to date",
  "SkipUpdate": "Skip Update",
  "UpdatesApp": "UPDATE",
  "CurrentVersionApp": "Current version {0} to",
  "ReleaseNote": "Release Note",
  "UpdatesAvailable": "Updates Available",
  "AppUpdate": "App Update",
  "UpdateFailedMsg": "An error occurred while checking for app update",
  "Retry": "Retry",

  "PersonalItemList": "Personal Item List",
  "basicFilterList": "Basic Filter List",
  "transactionList": "Transaction List",
  "PersonalItemDescription": "Keep items for any personal purpose",
  "AddType": "Add Type",
  "History": "history",
  "NewPersonalItemList":"New personal item list",
  "Name":"Name",
  "Type":"Type",
  "CanAccess":"Can access",
  "CanModify":"Can modify & access",
  "OnlyMe":"Only me",
  "Everyone":"Everyone",
  "MeAndStackholder":"Me and {0} Stackholder",
  "Stackholder":"Stackholder",
  "NameRequired":"Name Required",

  "CheckPriceDescirption":"Check any product price",
  "CheckPrice":"Check Price",
  "ScanCodeToCheckPrice": "Scan code to check price",

  "PriceLevel": "Price level",
  "Discount": "Discount",
  "Promotion": "Promotion",
  "EndIn": "end in",
  "NoCodeMsg": "Code not found",
  "NoItemMsg": "Unable to find product with this code({0})",

  "Receive":"Receive",
  "ReceiveTransferStock":"Receive Transfer Stock",
  "ReceiveStockTransferDescirption":"Find, count and confirm before receive items to your stock.",
  "ReceiveTransferStockSuccess":"Receive Transfer Stock Success!",
  "FinishReceiveTransferStocAlertMessage":
      "Are you sure to finish recieve transfer stock with above result, this action can't be undone?",

  "EnableSoftNumpad":"Enable soft numpad",
  "Scanner":"Scanner",
  "Camera":"Camera",
};
