final Map<String, String> khmer = {
  "DomainNotValid":"ឌូមែន មិន​ត្រឹមត្រូវ",

  "Login": "ចូល",
  "Logout": "ចាកចេញ",
  "LogoutOfYourAccount":"ចេញពីគណនីរបស់អ្នក?",
  "Domain": "ឌូមែន",
  "Username": "ឈ្មោះអ្នកប្រើប្រាស់",
  "Password": "អក្សរសម្ងាត់",
  "Okay": "យល់ព្រម",
  "Confirm": "បញ្ជាក់",
  "Success": "ជោគជ័យ",
  "Failure": "បរាជ័យ",
  "Close":"បិទ",
  "SomethingWentWrong":"មានអ្វីមួយខុសប្រក្រតី។ សូមពិនិត្យ ហើយព្យាយាមម្តងទៀតនៅពេលក្រោយ ឬទាក់ទងមកកាន់ផ្នែកសេវាកម្មរបស់យើង",
  "ComingSoon":"មកដល់ឆាប់ៗនេះ!",
  "FeatureComingSoon":"This feature will available soon.",

  // api respose
  "Login failed!": "ការចូលបានបរាជ័យ!",
  "The user name or password provided is incorrect!":
      "ឈ្មោះ​អ្នក​ប្រើ ឬ​ពាក្យ​សម្ងាត់​ដែល​បាន​ផ្ដល់​គឺ​មិន​ត្រឹមត្រូវ!",

  // feature check stock
  "CheckStock": "ពិនិត្យស្តុក",
  "CheckStockDescirption":
      "ពិនិត្យមើលស្តុកដែលមាន និងទីតាំងនៅក្នុងឃ្លាំង",
  "InvalidCode":"លេខកូដមិនត្រឹមត្រូវ",
  "ScanningCode":"ស្កេនលេខកូដ",
  "AimYourCameraOnQrCodeBarcodeToCheck":"សូមតម្រង់របស់កាមេរ៉ាអ្នកនៅលើ Qr Code/Barcode",
  "MyResponseLocation":"ទីតាំងទទួលខុសត្រូវរបស់ខ្ញុំ",
  "ScanninOtherLocationgCode":"ទីតាំងផ្សេងទៀត",
  "AvailableQuantity":"បរិមាណដែលអាចប្រើបាន",
  "QuantityOnHand":"បរិមាណក្នុងដៃ",
  "ScanCodeToCheckStock":"ស្កេនលេខកូដដើម្បីពិនិត្យស្តុក",
  "RelatedItem":"ផលិតផលដែលទាក់ទង",

  // feature count
  "Count": "រាប់",
  "Counts": "រាប់",
  "CountQuantity":"ចំនួនដែលរាប់",
  "CountDescirption": "ចាប់ផ្តើមរាប់ទំនិញរបស់អ្នក",
  "ItemCount": "ទំនិញដែលរាប់",
  "ItemToCount": "ទំនិញដែលត្រូវរាប់",
  "Pending": "កំពុង​រង់ចាំ",
  "Inprocess": "ដំណើរការ",
  "Recount": "រាប់ឡើងវិញ",
  "PendingRecount":"រង់ចាំរាប់ឡើងវិញ",
  "ProcessRecount":"កំពុងរាប់ឡើងវិញ",
  "ItemCode": "លេខកូដទំនិញ",
  "ItemBarcode": "បារកូដទំនិញ",
  "ItemDescription": "ការពិពណ៌នាទំនិញ",
  "LastCount":"ការរាប់ក្រោយបង្អស់",
  "All": "ទាំងអស់",
  "Counted": "បានរាប់",
  "Uncounted": "មិនបានរាប់",
  "Matched": "ត្រឹមត្រូវ",
  "Unmatched": "មិនត្រឹមត្រូវ",
  "Finish": "បញ្ចប់",
  "CountHistory": "ប្រវត្តិនៃការរាប់",
  "ViewAll": "មើលទាំងអស់",
  "CountType": "ប្រភេទរាប់",
  "AutoIncrease": "បង្កើន​ដោយ​ស្វ័យ​ប្រវត្តិ",
  "ManualInput": "ការបញ្ចូលដោយដៃ",
  "FinishCountSuccess":"បញ្ចប់ការរាប់ជោគជ័យ!",
  "StartCount":"ចាប់ផ្តើមរាប់",
  "StartCountMsg":"ចាប់ផ្តើមដំណើរការរាប់?",
  "CountNotYetStart":"ការរាប់មិនទាន់ចាប់ផ្តើមទេ",
  "CountNotYetStartMsg":"ការរាប់នេះមិនទាន់បានចាប់ផ្តើមនៅឡើយទេ សូមរង់ចាំរហូតដល់ការរាប់នេះចាប់ផ្តើម",
  "FinishCount":"បញ្ចប់ការរាប់",

  "Scan": "ស្កេន",
  "AutoScan": "ស្កែនស្វ័យប្រវត្តិ",
  "Product": "ផលិតផល",
  "Add": "បន្ថែម",
  "Replace": "ជំនួស",
  "FinishCountAlertMessage":"តើអ្នកប្រាកដថានឹងបញ្ចប់ការរាប់ជាមួយនឹងលទ្ធផលខាងលើ សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ?",

  "Filter":"តម្រង",
  "Brand":"ម៉ាក",
  "Category":"ប្រភេទ",
  "SortBy":"តម្រៀបតាម",
  "Reset":"កំណត់ឡើងវិញ",
  "Start":"ចាប់ផ្តើម",
  "Cancel":"បោះបង់",
  "Search":"ស្វែងរក...",
  "Quantity":"ចំនួន",

  "AppVersion": "កំណែកម្មវិធី",
  "AppVersionUpToDate": "ជំនាន់កម្មវិធីរបស់អ្នក {0} គឺជាជំនាន់ថ្មីចុងក្រោយ",
  "SkipUpdate": "រំលង ធ្វើបច្ចុប្បន្នភាព",
  "UpdatesApp": "ធ្វើបច្ចុប្បន្នភាព",
  "CurrentVersionApp": "ជំនាន់កម្មវិធីបច្ចុប្បន្ន {0} ទៅ",
  "ReleaseNote": "កំណត់ចំណាំលើកំណែទម្រង់ថ្មី",
  "UpdatesAvailable": "បច្ចុប្បន្នភាពកម្មវិធី",
  "AppUpdate": "ការធ្វើបច្ចុប្បន្នភាពកម្មវិធី",
  "UpdateFailedMsg":"កំហុសមួយបានកើតឡើងខណៈពេលកំពុងពិនិត្យមើលបច្ចុប្បន្នភាពកម្មវិធី",
  "Retry":"ព្យាយាមម្តងទៀត",

  "PersonalItemList":"បញ្ជីរបស់របរផ្ទាល់ខ្លួន",
  "basicFilterList":"បញ្ជីតម្រងមូលដ្ឋាន",
  "transactionList":"បញ្ជីប្រតិបត្តិការ",
  "PersonalItemDescription":"រក្សាបញ្ជីរបស់របរសម្រាប់គោលបំណងផ្ទាល់ខ្លួនណាមួយ",

  "CheckPriceDescirption":"ពិនិត្យមើលតម្លៃផលិតផលណាមួយ",
  "CheckPrice":"ពិនិត្យមើលតម្លៃ",
  "ScanCodeToCheckPrice": "ស្កេនលេខកូដដើម្បីពិនិត្យមើលតម្លៃ",

  "PriceLevel":"កម្រិតតម្លៃ",
  "Discount":"បញ្ចុះតម្លៃ",
  "Promotion":"ប្រូម៉ូសិន",
  "EndIn":"បញ្ចប់",
  "NoCodeMsg": "រកមិនឃើញលេខកូដ",
  "NoItemMsg": "មិនអាចស្វែងរកផលិតផលដោយប្រើលេខកូដ({0})បានទេ",

  "Receive":"ទទួល",
  "ReceiveTransferStock":"ទទួលការផ្ទេរស្តុក",
  "ReceiveStockTransferDescirption":"ស្វែងរក រាប់ និងបញ្ជាក់ មុនពេលទទួលទំនិញទៅកាន់ស្តុករបស់អ្នក",
  "ReceiveTransferStockSuccess":"ទទួលការផ្ទេរស្តុក ជោកជ័យ!",
  "FinishReceiveTransferStocAlertMessage":
      "តើអ្នកប្រាកដថាបានបញ្ចប់ការទទួលការផ្ទេរស្តុកជាមួយនឹងលទ្ធផលខាងលើ សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ?",
  };